export const QUERY_KEYS = {
  FETCH_INTAGRATIONS: 'FETCH_INTAGRATIONS',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_MESSAGES: 'FETCH_MESSAGES',
  SEND_MESSAGE: 'SEND_MESSAGE',
  GREETING: 'GREETING',
  SEND_MESSAGE_BY_BUTTON: 'SEND_MESSAGE_BY_BUTTON',
  FETCH_ME: 'FETCH_ME',
  GENERATED_IMAGE: 'GENERATED_IMAGE',
} as const;
